/**
 * Canonical vocabulary for the executable fault-operations ontology.
 * String enums are used because every value crosses the JSON/event-log seam.
 *
 * V1 迁移后仅保留本体图谱层生产消费的枚举；
 * V2 诊断状态枚举（CandidateStatus/TaskStatus/EvidenceEffect/RuntimeMode/…）
 * 统一在 src/v2/runtime-types.ts，避免双套口径漂移。
 */

export enum OntologyObjectType {
  ASSET = 'ASSET',
  // 细粒度资源类型（docs/03 §3）；ASSET 作为未明确资源/硬件杂项的 fallback。
  BUSINESS_SERVICE = 'BUSINESS_SERVICE',
  HOST = 'HOST',
  FABRIC = 'FABRIC',
  PORT = 'PORT',
  STORAGE_SYSTEM = 'STORAGE_SYSTEM',
  CONTROLLER = 'CONTROLLER',
  SERVICE = 'SERVICE',
  LUN = 'LUN',
  POOL = 'POOL',
  ENCLOSURE = 'ENCLOSURE',
  DISK = 'DISK',
  REPLICATION_SESSION = 'REPLICATION_SESSION',
  REMOTE_DEVICE = 'REMOTE_DEVICE',
  KNOWLEDGE = 'KNOWLEDGE',
  OBSERVATION = 'OBSERVATION',
  FACT = 'FACT',
  CANDIDATE = 'CANDIDATE',
  EVIDENCE = 'EVIDENCE',
  PLAN = 'PLAN',
  TASK = 'TASK',
  FUNCTION_CALL = 'FUNCTION_CALL',
  ACTION_PROPOSAL = 'ACTION_PROPOSAL',
  DECISION = 'DECISION',
  SCENARIO = 'SCENARIO',
}

export enum OntologyLinkType {
  ACCESSES = 'ACCESSES',
  CONNECTS_TO = 'CONNECTS_TO',
  DEPENDS_ON = 'DEPENDS_ON',
  HOSTS = 'HOSTS',
  PROVIDES_SERVICE = 'PROVIDES_SERVICE',
  BACKED_BY = 'BACKED_BY',
  BELONGS_TO = 'BELONGS_TO',
  PRIMARY_BACKUP_OF = 'PRIMARY_BACKUP_OF',
  ACTIVE_STANDBY_WITH = 'ACTIVE_STANDBY_WITH',
  SHARES = 'SHARES',
  REPLICATES_TO = 'REPLICATES_TO',
  OBSERVED_ON = 'OBSERVED_ON',
  EXPLAINS = 'EXPLAINS',
  CAUSES = 'CAUSES',
  INSTANCE_OF = 'INSTANCE_OF',
  APPLICABLE_TO = 'APPLICABLE_TO',
  EXHIBITS = 'EXHIBITS',
  SUSCEPTIBLE_TO = 'SUSCEPTIBLE_TO',
  CAUSED_BY = 'CAUSED_BY',
  TRIGGERED_BY = 'TRIGGERED_BY',
  LEADS_TO = 'LEADS_TO',
  CASE_MATCH = 'CASE_MATCH',
  EVIDENCED_BY = 'EVIDENCED_BY',
  // KnowledgeGraphPackage 3.0.0 关系注册表（docs/19 §4.5）
  HAS_RESOURCE_TYPE = 'HAS_RESOURCE_TYPE',
  HAS_SCENARIO = 'HAS_SCENARIO',
  APPLIES_TO_TYPE = 'APPLIES_TO_TYPE',
  HAS_FAULT_MODE = 'HAS_FAULT_MODE',
  EXPLAINS_MODE = 'EXPLAINS_MODE',
  MANIFESTS_AS = 'MANIFESTS_AS',
  REQUIRES_EVIDENCE = 'REQUIRES_EVIDENCE',
  SATISFIED_BY_RULE = 'SATISFIED_BY_RULE',
  SUPPORTED_BY_SKILL = 'SUPPORTED_BY_SKILL',
  TEMPLATE_HAS_MEMBER = 'TEMPLATE_HAS_MEMBER',
  EXEMPLIFIES = 'EXEMPLIFIES',
  OBSERVED_ON_TYPE = 'OBSERVED_ON_TYPE',
  MAPS_TO = 'MAPS_TO',
  DERIVED_FROM = 'DERIVED_FROM',
  TARGETS = 'TARGETS',
  PRODUCED_BY = 'PRODUCED_BY',
  SUPPORTS = 'SUPPORTS',
  WEAKENS = 'WEAKENS',
  CONFLICTS_WITH = 'CONFLICTS_WITH',
  CONTAINS = 'CONTAINS',
  SUPERSEDES = 'SUPERSEDES',
  BASED_ON = 'BASED_ON',
  IMPACTS = 'IMPACTS',
  RECOVERS_VIA = 'RECOVERS_VIA',
  PROPOSES = 'PROPOSES',
  UNKNOWN = 'UNKNOWN',
}

export enum LensId {
  TOPOLOGY = 'TOPOLOGY',
  KNOWLEDGE = 'KNOWLEDGE',
  DIAGNOSIS = 'DIAGNOSIS',
  IMPACT = 'IMPACT',
  AUDIT = 'AUDIT',
}

export enum FunctionEffect {
  READ_ONLY = 'READ_ONLY',
}
