/**
 * Canonical vocabulary for the executable fault-operations ontology.
 * String enums are used because every value crosses the JSON/event-log seam.
 */

export enum OntologyObjectType {
  ASSET = 'ASSET',
  KNOWLEDGE = 'KNOWLEDGE',
  OBSERVATION = 'OBSERVATION',
  FACT = 'FACT',
  CANDIDATE = 'CANDIDATE',
  EVIDENCE = 'EVIDENCE',
  PLAN = 'PLAN',
  TASK = 'TASK',
  FUNCTION_CALL = 'FUNCTION_CALL',
  ACTION_PROPOSAL = 'ACTION_PROPOSAL',
  DECISION = 'DECISION',
  SCENARIO = 'SCENARIO',
}

export enum OntologyLinkType {
  ACCESSES = 'ACCESSES',
  CONNECTS_TO = 'CONNECTS_TO',
  DEPENDS_ON = 'DEPENDS_ON',
  HOSTS = 'HOSTS',
  PROVIDES_SERVICE = 'PROVIDES_SERVICE',
  BACKED_BY = 'BACKED_BY',
  BELONGS_TO = 'BELONGS_TO',
  PRIMARY_BACKUP_OF = 'PRIMARY_BACKUP_OF',
  INSTANCE_OF = 'INSTANCE_OF',
  APPLICABLE_TO = 'APPLICABLE_TO',
  EXHIBITS = 'EXHIBITS',
  SUSCEPTIBLE_TO = 'SUSCEPTIBLE_TO',
  CAUSED_BY = 'CAUSED_BY',
  TRIGGERED_BY = 'TRIGGERED_BY',
  LEADS_TO = 'LEADS_TO',
  CASE_MATCH = 'CASE_MATCH',
  EVIDENCED_BY = 'EVIDENCED_BY',
  DERIVED_FROM = 'DERIVED_FROM',
  TARGETS = 'TARGETS',
  PRODUCED_BY = 'PRODUCED_BY',
  SUPPORTS = 'SUPPORTS',
  WEAKENS = 'WEAKENS',
  CONFLICTS_WITH = 'CONFLICTS_WITH',
  CONTAINS = 'CONTAINS',
  SUPERSEDES = 'SUPERSEDES',
  BASED_ON = 'BASED_ON',
  IMPACTS = 'IMPACTS',
  RECOVERS_VIA = 'RECOVERS_VIA',
  PROPOSES = 'PROPOSES',
  UNKNOWN = 'UNKNOWN',
}

export enum LensId {
  TOPOLOGY = 'TOPOLOGY',
  KNOWLEDGE = 'KNOWLEDGE',
  DIAGNOSIS = 'DIAGNOSIS',
  IMPACT = 'IMPACT',
  AUDIT = 'AUDIT',
}

export enum DiagnosisPhase {
  MODEL_OVERVIEW = 'MODEL_OVERVIEW',
  SESSION_INITIALIZING = 'SESSION_INITIALIZING',
  SCOPE_LOCALIZATION = 'SCOPE_LOCALIZATION',
  CANDIDATE_GENERATION = 'CANDIDATE_GENERATION',
  EVIDENCE_COLLECTION = 'EVIDENCE_COLLECTION',
  COMPETING_EXPLANATION = 'COMPETING_EXPLANATION',
  CONCLUSION_CHECK = 'CONCLUSION_CHECK',
  DIAGNOSIS_REVIEW = 'DIAGNOSIS_REVIEW',
}

export enum RouteStatus {
  MATCHED = 'MATCHED',
  AMBIGUOUS = 'AMBIGUOUS',
  NOT_MATCHED = 'NOT_MATCHED',
  INVALID_INPUT = 'INVALID_INPUT',
}

export enum TaskStatus {
  PLANNED = 'PLANNED',
  READY = 'READY',
  RUNNING = 'RUNNING',
  SUCCEEDED = 'SUCCEEDED',
  FAILED = 'FAILED',
  PARTIAL = 'PARTIAL',
  TIMEOUT = 'TIMEOUT',
  DATA_MISSING = 'DATA_MISSING',
  PAUSED = 'PAUSED',
  CANCELLED = 'CANCELLED',
  SKIPPED = 'SKIPPED',
}

export enum CandidateStatus {
  INITIAL = 'INITIAL',
  ACTIVE = 'ACTIVE',
  LEADING = 'LEADING',
  WEAKENED = 'WEAKENED',
  CONFLICTING = 'CONFLICTING',
  CONFIRMED = 'CONFIRMED',
  NOT_CONFIRMED = 'NOT_CONFIRMED',
}

export enum EvidenceRelation {
  SUPPORTS = 'SUPPORTS',
  WEAKENS = 'WEAKENS',
  CONFLICTS = 'CONFLICTS',
  NEUTRAL = 'NEUTRAL',
}

export enum ConclusionType {
  ROOT_CAUSE_CONFIRMED = 'ROOT_CAUSE_CONFIRMED',
  PROBABLE_CAUSES = 'PROBABLE_CAUSES',
  INSUFFICIENT_EVIDENCE = 'INSUFFICIENT_EVIDENCE',
}

export enum PlannerOperationKind {
  FUNCTION_CALL = 'FUNCTION_CALL',
  ACTION_PROPOSAL = 'ACTION_PROPOSAL',
}

export enum FunctionEffect {
  READ_ONLY = 'READ_ONLY',
}

export enum ActionProposalStatus {
  PROPOSED = 'PROPOSED',
  APPROVAL_REQUIRED = 'APPROVAL_REQUIRED',
  REJECTED = 'REJECTED',
}

export enum EventType {
  DIAGNOSIS_INITIALIZED = 'DIAGNOSIS_INITIALIZED',
  DIAGNOSIS_PHASE_CHANGED = 'DIAGNOSIS_PHASE_CHANGED',
  PLAN_CREATED = 'PLAN_CREATED',
  TASK_CREATED = 'TASK_CREATED',
  TASK_STATUS_CHANGED = 'TASK_STATUS_CHANGED',
  FUNCTION_CALL_REQUESTED = 'FUNCTION_CALL_REQUESTED',
  FUNCTION_CALL_COMPLETED = 'FUNCTION_CALL_COMPLETED',
  FACT_DISCOVERED = 'FACT_DISCOVERED',
  CANDIDATES_GENERATED = 'CANDIDATES_GENERATED',
  EVIDENCE_CREATED = 'EVIDENCE_CREATED',
  CANDIDATE_UPDATED = 'CANDIDATE_UPDATED',
  PLAN_REPLANNED = 'PLAN_REPLANNED',
  ACTION_PROPOSED = 'ACTION_PROPOSED',
  DECISION_RECORDED = 'DECISION_RECORDED',
  ROOT_CAUSE_CONFIRMED = 'ROOT_CAUSE_CONFIRMED',
  DIAGNOSIS_COMPLETED = 'DIAGNOSIS_COMPLETED',
}
